module.exports = {
	faq: [
		'Soylent is a simple, efficient and affordable drink that possesses what a body needs to be healthy.',
		'Soylent is a new option for maintaining a balanced state of ideal nutrition, just like traditional food.',
		'Soylent’s nutritional makeup includes protein, carbohydrates, fats, fiber, and vitamins and minerals such as potassium, iron and calcium.',
		'It includes all of the elements of a healthy diet, without excess amounts of sugars, saturated fats, or cholesterol.',
		'Soylent is a convenient powder that is mixed with water.',
		'Soylent Bar is ready to unwrap and enjoy.',
		'Healthy food can be expensive and takes time to prepare. At around $3/meal, Soylent is affordable.',
		'Soylent is designed as a simple staple food, and people incorporate it into their lives to varying degrees.',
		'Soylent Drink and Coffiest are ready to drink right from the bottle.',
		'Some people use it almost exclusively, while others use it 2-3 times per week.',
		'As a nutritionally complete food source, Soylent should be considered a food product just like any other.',
		'You can include Soylent in your diet for as long as you’d like, in any amount that suits your needs.',
		'There is no right or wrong amount of Soylent to eat',
		'There is no right or wrong amount of Soylent to eat - the whole idea is to find a balance that works for you.',
		'The average adult requires 2,000 calories per day, which is equivalent to one pouch of Soylent Powder',
		'Please feel free to consult our nutrition facts for Soylent Powder, and Soylent Drink for more information.',
		'When preparing Soylent Powder, you may adjust the size of each serving to your liking.',
		'You are free to consume your Soylent in whatever amount works for you.',
		'Most people consume fewer than 2000 calories of Soylent daily.',
		'Most people consume fewer than 2000 calories of Soylent daily.  This means that a pouch of Soylent Powder often lasts for two or more days.',
		'At this time Soylent has not been evaluated specifically for weight loss purposes.',
		'Soylent contains plenty of insoluble fiber so bowel movements are more or less unchanged.',
		'Soylent products are currently sold exclusively through Soylent.com and Amazon.com.',
		'Soylent is made using ingredients that you probably already have in your kitchen.',
		'Soylent 2.0 is designed to have a low environmental impact and comes in a recyclable bottle.',
		'A one-year shelf life gives you the freedom to enjoy Soylent 2.0 whenever is convenient.',
		'Soylent™ was developed from a need for a simpler food source.',
		'Soylent is a food product (classified as a food, not a supplement, by the FDA) designed for use as a staple meal by all adults.',
		'The question we hear most often is, “What is Soylent?”.',
		'we recognize that the idea of a nutritionally complete meal-in-a-bottle is still an unfamiliar concept to most of the larger population',
		'Today we are pleased to announce that we have reached a new milestone, a point where we can cut the price of Soylent powder for everyone.',
		'Our goal at Soylent is to engineer nutritionally-complete food products that are optimized for modern consumers’ lifestyles and budgets',
		'Soylent’s nutritional makeup is comprehensive.',
		'The Soylent recipe... is regulated as a food by the Food and Drug Administration (FDA).',
		'Soylent contains ingredients from countries that may include but are not limited to: United States of America, China.'
	]
}